# Generated by Django 3.2 on 2021-08-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_date',
            field=models.DateField(),
        ),
    ]
